set -eu
DIR_START_ALL="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo start-base.sh running ...
$DIR_START_ALL/base/start-base.sh
echo start-hobo.sh running ... 
$DIR_START_ALL/hobo/start-hobo.sh
echo start-authentic.sh running ... 
$DIR_START_ALL/authentic/start-authentic.sh
echo start-combo.sh running ... 
$DIR_START_ALL/combo/start-combo.sh
echo start-fargo.sh running ... 
$DIR_START_ALL/fargo/start-fargo.sh
echo start-passerelle.sh running ... 
$DIR_START_ALL/passerelle/start-passerelle.sh
echo start-wcs.sh running ... 
$DIR_START_ALL/wcs/start-wcs.sh
echo start-chrono.sh running ... 
$DIR_START_ALL/chrono/start-chrono.sh
echo start-bijoe.sh running ... 
$DIR_START_ALL/bijoe/start-bijoe.sh

echo start nginx and supervisor running ... 
service nginx restart
service supervisor restart