set -eu
DIR_STOP_ALL="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo stop-nginx running ...
service nginx stop

echo stop-hobo.sh running ... 
$DIR_STOP_ALL/hobo/stop-hobo.sh
echo stop-authentic.sh running ... 
$DIR_STOP_ALL/authentic/stop-authentic.sh
echo stop-combo.sh running ... 
$DIR_STOP_ALL/combo/stop-combo.sh
echo stop-fargo.sh running ... 
$DIR_STOP_ALL/fargo/stop-fargo.sh
echo stop-passerelle.sh running ... 
$DIR_STOP_ALL/passerelle/stop-passerelle.sh
echo stop-wcs.sh running ... 
$DIR_STOP_ALL/wcs/stop-wcs.sh
echo stop-chrono.sh running ... 
$DIR_STOP_ALL/chrono/stop-chrono.sh
echo stop-bijoe.sh running ... 
$DIR_STOP_ALL/bijoe/stop-bijoe.sh


echo Stop HOBO Agent running ...
service supervisor stop